export const data = [
    { 'heading': 'How I work?', 'desc': 'It all starts with a brief discussion on the type of website you want and the functionality the website needs. Then I follow up with these steps mentioned below.', 'img': 'assets/images/discussion.jpg' },
    { 'heading': 'Design inspiration', 'desc': 'This step involves sharing bunch of design inspiration that I collect from around the internet. It may or may not influence the final product I create but its a good practice to have a base.', 'img': 'assets/images/moodboard.jpg' },
    { 'heading': 'Wireframe', 'desc': 'With the inputs I get, I will create a wireframe design. The objective of this step is to have a rough understanding of all the elements you need in an organised, functional layout. At the end of this process I will offer a quotation for the whole project, both design and development.', 'img': 'assets/images/wireframe.jpg' },
    { 'heading': 'Design showcase', 'desc': 'This is an important step in the design phase. I will create a complete design for the website and we will discuss in depth about any modification we need. Only after your approval and agreement, I will proceed to developement. Please note after we go though with this stem it is highly discouraged to modify the design at a later stage.', 'img': '/assets/images/landing_page.png' },
    { 'heading': 'Web Developement', 'desc': 'From the design files, I will create the website taking into consideration your inputs and requirements. At the end of this stage you will have a fully functional website that is optimized for desktop and laptops. Only after your approval, I will continue to the next stage of developement.', 'img': 'assets/images/code.jpg' },
    { 'heading': 'Mobile and tablet optimization', 'desc': 'I begin working on making the website mobile friendly. This is also a crucial step as a lot of traffic is generated via mobile devices these days. During this stage the website is made responsible for all screen sizes.', 'img': 'assets/images/mobile.webp' },
    { 'heading': 'Miscellaneous task and delivery', 'desc': 'Content upload, hoising and other such activity is carried out in this step and finally the product is delivered to you.', 'img': 'assets/images/delivery.jpg' },
    // { 'heading': 'Gatsby project', 'excerpt': 'A fantastic choice for serverless website', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },

]