export const data = [
    { 'heading': 'What Makes a good website?', 'desc': 'A good website should excel in both form and function. It should have a clear purpose. It should be visually pleasing and easy to navigate. It should perform well for a wide range of visitors and be technically stable and secure. Good websites are attractive, functional, and useful. Your website is sometimes the only thing your customer sees. You want that it to be so awesome that it attracts people.', 'img': 'https://images.unsplash.com/photo-1622044769168-ee7326e25704?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80' },
    { 'heading': 'Simplicity is the key', 'desc': 'Several studies by Google have resulted in these two key findings:\nUsers will judge websites as beautiful or not within 1/50th to 1/20th of a second.\nVisually complex websites are consistently rated as less beautiful than their simpler counterparts.\nYour website is the first place your customers get to learn more about your brand and business. As such, it is very important to have a usable, functional and elegant website.\nA simple website is the one that gets rid of all unnecessary clutter and instead focuses on cleanliness, organization and simplicity. It is all about communicating as much as possible without over complicating things.', 'img': 'https://images.unsplash.com/photo-1475257026007-0753d5429e10?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80' },
    { 'heading': 'Website updates', 'desc': 'Websites tend to get boring over time, which often is the case if it isn\'t maintained regularly. Although large layout changes can be confusing to regular visits and be detrimental, tiny changes always leave a positive impact. Don\'t be that guy who finds a WordPress theme a sticks to it for life, instead explore more modern, worthwhile options that a much cheaper and refreshing to the eye while being highly customizable and hassle free', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },
    // { 'heading': 'Gatsby project', 'excerpt': 'A fantastic choice for serverless website', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },
    // { 'heading': 'Gatsby project', 'excerpt': 'A fantastic choice for serverless website', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },
    // { 'heading': 'GoDaddy project', 'excerpt': 'When you want something quick', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },
    // { 'heading': 'Wix project', 'excerpt': 'Lot of good layout but expensive', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },
    // { 'heading': 'Gatsby project', 'excerpt': 'A fantastic choice for serverless website', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },

]