export const data = [
    { 'id': 1, 'logo': 'assets/images/hero/11.webp', 'price': 100, 'link': '#', 'heading': 'Ecommerce Website', 'excerpt': 'A fantastic choice if you have stuff to sell', 'img': 'assets/images/hero/11.webp' },
    { 'id': 2, 'logo': 'assets/images/hero/12.webp', 'price': 100, 'link': 'https://nextjs-blog-kuldeep.vercel.app/', 'heading': 'Blogging website', 'excerpt': 'Perfect for those who wish to show what they\'re upto', 'img': 'assets/images/hero/12.webp' },
    { 'id': 3, 'logo': 'assets/images/hero/15.png', 'price': 100, 'link': 'https://web3-framer-motion-kuldeep.vercel.app/', 'heading': 'Advertisement website', 'excerpt': 'Ideal for small business that need a presence online', 'img': 'assets/images/hero/15.png' },
    { 'id': 4, 'logo': 'assets/images/hero/3.jpg', 'price': 100, 'link': 'https://paint-your-world-kuldeep.netlify.app', 'heading': 'Clone website', 'excerpt': 'You want something similar to your competitor', 'img': 'assets/images/hero/13.jpg' },
    { 'id': 5, 'logo': 'assets/images/hero/2.webp', 'price': 100, 'link': 'https://www.figma.com/file/BFQ2lkUTUVrBLtosG44jdr/Demo?node-id=42%3A82&t=BzXeZdf509C27ELU-1', 'heading': 'Design only', 'excerpt': 'If you\'re interested to buy only the design', 'img': 'assets/images/hero/2.webp' },
    { 'id': 6, 'logo': 'assets/images/hero/14.jpg', 'price': 100, 'link': '#', 'heading': 'Service pack', 'excerpt': 'Great if you want my services beyond free service period', 'img': 'assets/images/hero/14.jpg' },
    // { 'heading': 'Gatsby project', 'excerpt': 'A fantastic choice for serverless website', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },
    // { 'heading': 'Gatsby project', 'excerpt': 'A fantastic choice for serverless website', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },
    // { 'heading': 'GoDaddy project', 'excerpt': 'When you want something quick', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },
    // { 'heading': 'Wix project', 'excerpt': 'Lot of good layout but expensive', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },
    // { 'heading': 'Gatsby project', 'excerpt': 'A fantastic choice for serverless website', 'img': 'https://images.unsplash.com/photo-1509773896068-7fd415d91e2e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80' },

]